### ISSUE TITLE
Not usable on Linux because of carriage return on shebang line

### ISSUE THREAD

**Issue by knopki** [roxiness/spank#1]
`spank@1.2.0` doesn't work on Linux:
```shell
> node_modules/.bin/spank
/usr/bin/env: ‘node\r’: No such file or directory
```

It's because of DOS-style CR-LF line endings and not Unix-style LF line endings:
```shell
➜ file node_modules/spank/cli.js
node_modules/spank/cli.js: Node.js script, ASCII text executable, with CRLF line terminators
```

Simple convertation (`sed -e 's/\r//g' -i node_modules/spank/cli.js`) fixes this.

**Comment by knopki** [comment]
Files in this repository are LF terminated (or LF-terminated when I clone the repo), but files in NPM are CRLF terminated. Looks like package was published from Windows and `git` was configured with `core.autocrlf=true` setting.

**Comment by jakobrosenberg** [comment]
Thanks for the heads up.

Could you check if this is still an issue in `1.3.1`?

**Comment by knopki** [comment]
`1.3.1` is working fine. Thank you!
