### ISSUE TITLE
Handle anchor elements missing href tag

### ISSUE THREAD

**Issue by derek-rein** [roxiness/spank#10]
Issue can be recreated by adding

`<a class="ml-4 text-gray-500">I'm an anchor element with no href tag</a>`

To the Tailwind Routify setup

**Comment by jakobrosenberg** [comment]
I probably just need a break, but I can't tell what the issue is.

**Comment by derek-rein** [comment]
If an a tag has no href attribute, the build process stalls. I'm building a static site using the tailwind/routify.
`<a>No href, does not build</a>`
The workaround is to link to the current page
`<a href="/#">This works</a>`

**Comment by jakobrosenberg** [comment]
Sorry about the late follow up @DerekRein. I'd completely forgotten about this issue.

What would be the best way to handle this? Ignoring the anchor or throwing an error?

**Comment by derek-rein** [comment]
Looking at w3.org specs on the anchor tag:
"If the a element has no href attribute, then the element represents a placeholder for where a link might otherwise have been placed, if it had been relevant."
http://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element
Reads like it's valid html, so I'd say ignore it.

**Comment by jakobrosenberg** [comment]
Thanks @DerekRein . I've patched spank and empty hrefs should be ignored in `^1.5.2`.
