### ISSUE TITLE
Generate a template backup of index.html

### ISSUE THREAD

**Issue by braebo** [roxiness/spank#12]
Refreshing an SPA uses the hydrated index.html- we need to generate a template backup of index.html to load instead.

**Comment by jakobrosenberg** [comment]
https://github.com/roxiness/spank/releases/new?tag=v1.8.0&body=-+feat%3A+added+copyEntrypointTo+option++99b9b2a%0A%0Ahttps%3A%2F%2Fgithub.com%2Froxiness%2Fspank%2Fcompare%2Fv1.7.1...v1.8.0&prerelease=false

**Comment by jakobrosenberg** [comment]
https://github.com/roxiness/spank/releases/tag/v1.8.0
