### ISSUE TITLE
Do we still need __app.html and serviceworker.js files?

### ISSUE THREAD

**Issue by rommyarb** [roxiness/spank#5]
Are they unused after I 'spank' it?

**Comment by jakobrosenberg** [comment]
That depends. If you intend on hosting a 100% static site, `__app.html` would be unused. There won't be any benefit in deleting the file though.

`serviceworker.js` is unrelated to `spank`. If you need offline availability you will need a serviceworker.

**Comment by rommyarb** [comment]
I understand now. Thank you very much!
